package com.sibelsama.lovelyy5.viewmodel

import androidx.lifecycle.ViewModel
import androidx.lifecycle.viewModelScope
import com.sibelsama.lovelyy5.model.Order
import com.sibelsama.lovelyy5.model.Product
import com.sibelsama.lovelyy5.model.ShippingDetails
import com.sibelsama.lovelyy5.repository.OrderRepository
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import kotlinx.coroutines.launch

open class AppViewModel : ViewModel() {
    val productList = listOf(
        Product(1, "Notebook HP", "Notebook 15,6\" Intel i5, 8GB, 256GB SSD", 499900.0),
        Product(2, "Mouse Logitech", "Mouse inalámbrico, ergonómico, USB", 19990.0),
        Product(3, "Smartphone Samsung", "Galaxy A14, 128GB, Dual SIM", 179990.0)
    )

    private val _cart = MutableStateFlow<Map<Product, Int>>(emptyMap())
    open val cart: StateFlow<Map<Product, Int>> = _cart.asStateFlow()

    private val orderRepository = OrderRepository()
    val orders: StateFlow<List<Order>> = orderRepository.orders

    fun addToCart(product: Product) {
        val currentCart = _cart.value.toMutableMap()
        currentCart[product] = (currentCart[product] ?: 0) + 1
        _cart.value = currentCart
    }

    fun removeFromCart(product: Product) {
        val currentCart = _cart.value.toMutableMap()
        currentCart.remove(product)
        _cart.value = currentCart
    }

    fun updateQuantity(product: Product, quantity: Int) {
        val currentCart = _cart.value.toMutableMap()
        if (quantity > 0) {
            currentCart[product] = quantity
        } else {
            currentCart.remove(product)
        }
        _cart.value = currentCart
    }

    fun createOrder(shippingDetails: ShippingDetails) {
        viewModelScope.launch {
            val subtotal = _cart.value.entries.sumOf { (product, quantity) -> product.price * quantity }
            val shippingCost = 5000.0
            val total = subtotal + shippingCost

            val order = Order(
                id = "", // Will be generated by the repository
                shippingDetails = shippingDetails,
                items = _cart.value,
                subtotal = subtotal,
                shippingCost = shippingCost,
                total = total
            )
            orderRepository.addOrder(order)
            _cart.value = emptyMap() // Clear the cart
        }
    }

    fun getOrderById(id: String): Order? {
        return orderRepository.getOrderById(id)
    }
}
